---
- hosts: 172.31.28.195
  become: yes
  tasks:
  - name: I want to install git
    apt:
     name: git
     state: present
    
  - name: I want to install wget
    apt:
     name: wget
     stateee: present
    
  - name: I want to instal tree
    apt:
     name: tree
     state: present       
    