---
- hosts: 172.31.28.195
  become: yes
  tasks:
  - name: creating file
    file:
      path: /home/ubuntu/myfile1
      state: touch

  - name: creating folder
    file:
      path: /home/ubuntu/myfolder1
      state: directory  