---
- hosts: 172.31.28.195
  become: yes
  tasks:
  - name: creating file
    file:
      path: /home/ubuntu/myfile1
      state: touch

  - name: creating folder
    file:
      path: /home/ubuntu/myfolder1
      state: directory  

  - name: Including task and creating file
    include_tasks: myfile.yml
        
  - name: copay content from other file
    copy:
      src: mytextfile.txt
      dest: /home/ubuntu/myfile3    