---
- hosts: myservers
  become: yes
  tasks:
  - name: I want to install git
    apt:
     name: git
     state: present
    tags: "mygit" 

  - name: I want to install wget
    apt:
     name: wget
     state: present
    tags: "mywget"

  - name: I want to instal tree
    apt:
     name: tree
     state: present       
    tags: "mytree" 