---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: Start service of apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: I want to install apache2
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="Red hat"

  - name: I want to install apache2
    service:
      name: httpd
      state: present
    when: ansible_os_family=="Red hat"   

