---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2
    apt:
      name: apache2
      state: present
      
  - name: Start service of apache2
    service:
      name: apache2
      state: started
    